#!/usr/bin/env bash
# OTTO - Auto Documentation Generator
# Generates infrastructure docs, network topology, service catalogs, runbooks, and ADRs.
# shellcheck disable=SC2034
set -euo pipefail

# Guard against double-sourcing
if [[ -n "${_OTTO_DOC_GENERATOR_LOADED:-}" ]]; then
    return 0 2>/dev/null || true
fi
_OTTO_DOC_GENERATOR_LOADED=1

OTTO_DIR="${OTTO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
OTTO_HOME="${OTTO_HOME:-${HOME}/.config/otto}"

# shellcheck source=/dev/null
source "${OTTO_DIR}/scripts/lib/colors.sh"
# shellcheck source=/dev/null
source "${OTTO_DIR}/scripts/lib/logging.sh"
# shellcheck source=/dev/null
source "${OTTO_DIR}/scripts/lib/json-utils.sh"

DOCGEN_OUTPUT_DIR="${OTTO_HOME}/docs/generated"

# --- Internal ---

_docgen_init() {
    mkdir -p "${DOCGEN_OUTPUT_DIR}"
}

# --- Public API ---

# Generate infrastructure overview from terraform state, K8s info, and cloud resources.
# Usage: docgen_infra_overview
# Outputs markdown to stdout.
docgen_infra_overview() {
    _docgen_init
    local output=""

    output+="# Infrastructure Overview\n\n"
    output+="*Generated by OTTO on $(date -Iseconds)*\n\n"

    # Terraform state
    output+="## Terraform Resources\n\n"
    if command -v terraform &>/dev/null; then
        local tf_state
        tf_state=$(terraform state list 2>/dev/null || true)
        if [[ -n "${tf_state}" ]]; then
            output+="| Resource | Type |\n"
            output+="| --- | --- |\n"
            while IFS= read -r resource; do
                local rtype
                rtype=$(echo "${resource}" | cut -d'.' -f1)
                output+="| ${resource} | ${rtype} |\n"
            done <<< "${tf_state}"
        else
            output+="No Terraform state found or not in a Terraform directory.\n"
        fi
    else
        output+="Terraform not installed.\n"
    fi
    output+="\n"

    # Kubernetes cluster info
    output+="## Kubernetes Cluster\n\n"
    if command -v kubectl &>/dev/null; then
        local cluster_info
        cluster_info=$(kubectl cluster-info 2>/dev/null | head -5 || echo "Cluster not reachable")
        output+="\`\`\`\n${cluster_info}\n\`\`\`\n\n"

        # Node summary
        local nodes
        nodes=$(kubectl get nodes -o wide --no-headers 2>/dev/null || true)
        if [[ -n "${nodes}" ]]; then
            output+="### Nodes\n\n"
            output+="\`\`\`\n$(kubectl get nodes -o wide 2>/dev/null || true)\n\`\`\`\n\n"
        fi

        # Namespace summary
        local ns_list
        ns_list=$(kubectl get namespaces --no-headers 2>/dev/null | awk '{print $1}' || true)
        if [[ -n "${ns_list}" ]]; then
            output+="### Namespaces\n\n"
            while IFS= read -r ns; do
                local pod_count
                pod_count=$(kubectl get pods -n "${ns}" --no-headers 2>/dev/null | wc -l || echo "0")
                output+="- **${ns}**: ${pod_count} pods\n"
            done <<< "${ns_list}"
            output+="\n"
        fi
    else
        output+="kubectl not installed.\n"
    fi
    output+="\n"

    # Cloud provider resources (AWS example)
    output+="## Cloud Resources\n\n"
    if command -v aws &>/dev/null; then
        local ec2_count
        ec2_count=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --output text 2>/dev/null | wc -w || echo "0")
        output+="- EC2 Instances: ${ec2_count}\n"
        local rds_count
        rds_count=$(aws rds describe-db-instances --query 'DBInstances[*].DBInstanceIdentifier' --output text 2>/dev/null | wc -w || echo "0")
        output+="- RDS Instances: ${rds_count}\n"
    elif command -v gcloud &>/dev/null; then
        output+="GCP detected. Use \`gcloud compute instances list\` for details.\n"
    elif command -v az &>/dev/null; then
        output+="Azure detected. Use \`az vm list\` for details.\n"
    else
        output+="No cloud CLI detected.\n"
    fi

    echo -e "${output}"
    echo -e "${output}" > "${DOCGEN_OUTPUT_DIR}/infra-overview.md"
    log_info "Infrastructure overview generated: ${DOCGEN_OUTPUT_DIR}/infra-overview.md"
}

# Generate network topology from K8s services, DNS, and load balancers.
# Usage: docgen_network_topology
docgen_network_topology() {
    _docgen_init
    local output=""

    output+="# Network Topology\n\n"
    output+="*Generated by OTTO on $(date -Iseconds)*\n\n"

    if command -v kubectl &>/dev/null; then
        # Services
        output+="## Services\n\n"
        local services
        services=$(kubectl get services --all-namespaces -o json 2>/dev/null || echo '{"items":[]}')
        local svc_count
        svc_count=$(echo "${services}" | jq '.items | length')

        if [[ "${svc_count}" -gt 0 ]]; then
            output+="| Namespace | Name | Type | ClusterIP | Ports |\n"
            output+="| --- | --- | --- | --- | --- |\n"
            output+="$(echo "${services}" | jq -r '.items[] | "| \(.metadata.namespace) | \(.metadata.name) | \(.spec.type) | \(.spec.clusterIP // "-") | \([.spec.ports[]? | "\(.port)/\(.protocol)"] | join(", ")) |"' 2>/dev/null || true)\n"
            output+="\n"
        fi

        # Ingresses
        output+="## Ingresses\n\n"
        local ingresses
        ingresses=$(kubectl get ingresses --all-namespaces -o json 2>/dev/null || echo '{"items":[]}')
        local ing_count
        ing_count=$(echo "${ingresses}" | jq '.items | length')

        if [[ "${ing_count}" -gt 0 ]]; then
            output+="| Namespace | Name | Hosts | Paths |\n"
            output+="| --- | --- | --- | --- |\n"
            output+="$(echo "${ingresses}" | jq -r '.items[] | "| \(.metadata.namespace) | \(.metadata.name) | \([.spec.rules[]?.host // "-"] | join(", ")) | \([.spec.rules[]?.http?.paths[]?.path // "/"] | join(", ")) |"' 2>/dev/null || true)\n"
        else
            output+="No ingresses found.\n"
        fi
        output+="\n"

        # Mermaid diagram
        output+="## Topology Diagram (Mermaid)\n\n"
        output+="\`\`\`mermaid\ngraph LR\n"
        output+="    Internet((Internet))\n"

        # Add ingress nodes
        echo "${ingresses}" | jq -r '.items[]? | "    Internet --> |\(.spec.rules[0]?.host // \"*\")| ING_\(.metadata.name)[\(.metadata.name)]"' 2>/dev/null | while IFS= read -r line; do
            output+="${line}\n"
        done

        # Add service connections
        echo "${services}" | jq -r '.items[]? | select(.spec.type == "LoadBalancer" or .spec.type == "NodePort") | "    Internet --> SVC_\(.metadata.name)[\(.metadata.name)]"' 2>/dev/null | while IFS= read -r line; do
            output+="${line}\n"
        done

        output+="\`\`\`\n"
    else
        output+="kubectl not available. Cannot generate network topology.\n"
    fi

    # DNS records
    output+="\n## DNS Records\n\n"
    if command -v dig &>/dev/null && [[ -n "${OTTO_DOMAIN:-}" ]]; then
        output+="\`\`\`\n$(dig "${OTTO_DOMAIN}" ANY +short 2>/dev/null || echo "No records found")\n\`\`\`\n"
    else
        output+="DNS lookup not available or OTTO_DOMAIN not set.\n"
    fi

    echo -e "${output}"
    echo -e "${output}" > "${DOCGEN_OUTPUT_DIR}/network-topology.md"
    log_info "Network topology generated: ${DOCGEN_OUTPUT_DIR}/network-topology.md"
}

# Generate service catalog from K8s deployments, docker containers, systemd services.
# Usage: docgen_service_catalog
docgen_service_catalog() {
    _docgen_init
    local output=""

    output+="# Service Catalog\n\n"
    output+="*Generated by OTTO on $(date -Iseconds)*\n\n"

    # Kubernetes deployments
    output+="## Kubernetes Deployments\n\n"
    if command -v kubectl &>/dev/null; then
        local deployments
        deployments=$(kubectl get deployments --all-namespaces -o json 2>/dev/null || echo '{"items":[]}')
        local dep_count
        dep_count=$(echo "${deployments}" | jq '.items | length')

        if [[ "${dep_count}" -gt 0 ]]; then
            output+="| Namespace | Name | Replicas | Ready | Image |\n"
            output+="| --- | --- | --- | --- | --- |\n"
            output+="$(echo "${deployments}" | jq -r '.items[] | "| \(.metadata.namespace) | \(.metadata.name) | \(.spec.replicas // 0) | \(.status.readyReplicas // 0) | \(.spec.template.spec.containers[0].image // "-") |"' 2>/dev/null || true)\n"
        else
            output+="No deployments found.\n"
        fi
    else
        output+="kubectl not available.\n"
    fi
    output+="\n"

    # Docker containers
    output+="## Docker Containers\n\n"
    if command -v docker &>/dev/null; then
        local containers
        containers=$(docker ps --format '{{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}' 2>/dev/null || true)
        if [[ -n "${containers}" ]]; then
            output+="| Name | Status | Ports | Image |\n"
            output+="| --- | --- | --- | --- |\n"
            while IFS=$'\t' read -r name status ports image; do
                output+="| ${name} | ${status} | ${ports} | ${image} |\n"
            done <<< "${containers}"
        else
            output+="No running containers.\n"
        fi
    else
        output+="Docker not available.\n"
    fi
    output+="\n"

    # Systemd services (user-notable ones)
    output+="## System Services\n\n"
    if command -v systemctl &>/dev/null; then
        output+="| Service | Status | Active |\n"
        output+="| --- | --- | --- |\n"
        local notable_services=("nginx" "apache2" "httpd" "postgresql" "mysql" "mariadb" "redis" "docker" "containerd" "kubelet" "haproxy" "prometheus" "grafana-server" "elasticsearch")
        for svc in "${notable_services[@]}"; do
            local status active
            status=$(systemctl is-enabled "${svc}" 2>/dev/null || echo "not-found")
            if [[ "${status}" != "not-found" ]]; then
                active=$(systemctl is-active "${svc}" 2>/dev/null || echo "unknown")
                output+="| ${svc} | ${status} | ${active} |\n"
            fi
        done
    fi

    echo -e "${output}"
    echo -e "${output}" > "${DOCGEN_OUTPUT_DIR}/service-catalog.md"
    log_info "Service catalog generated: ${DOCGEN_OUTPUT_DIR}/service-catalog.md"
}

# Generate runbook from incident resolution steps.
# Usage: docgen_runbook_from_incident <incident_id>
docgen_runbook_from_incident() {
    local incident_id="$1"
    _docgen_init

    # Source incident memory if not already loaded
    if ! declare -f incident_memory_load &>/dev/null; then
        # shellcheck source=/dev/null
        source "${OTTO_DIR}/scripts/core/incident-memory.sh"
    fi

    local incident
    incident=$(incident_memory_load "${incident_id}")

    if [[ "${incident}" == "null" || -z "${incident}" ]]; then
        log_error "Cannot generate runbook: incident ${incident_id} not found"
        return 1
    fi

    local output=""
    local title
    title=$(echo "${incident}" | jq -r '.title // .incident_id')

    output+="# Runbook: ${title}\n\n"
    output+="*Auto-generated from incident ${incident_id} on $(date -Iseconds)*\n\n"

    # Symptoms
    output+="## Symptoms\n\n"
    local symptoms
    symptoms=$(echo "${incident}" | jq -r '.symptoms // [] | .[]' 2>/dev/null || true)
    if [[ -n "${symptoms}" ]]; then
        while IFS= read -r symptom; do
            output+="- ${symptom}\n"
        done <<< "${symptoms}"
    else
        output+="_(No symptoms recorded)_\n"
    fi
    output+="\n"

    # Diagnosis steps
    output+="## Diagnosis\n\n"
    local checks
    checks=$(echo "${incident}" | jq -r '.checks_run // [] | .[]' 2>/dev/null || true)
    if [[ -n "${checks}" ]]; then
        local step=1
        while IFS= read -r check; do
            output+="${step}. ${check}\n"
            step=$((step + 1))
        done <<< "${checks}"
    else
        output+="_(No diagnostic steps recorded)_\n"
    fi
    output+="\n"

    # Resolution steps
    output+="## Resolution\n\n"
    local actions
    actions=$(echo "${incident}" | jq -r '.actions_taken // [] | .[]' 2>/dev/null || true)
    if [[ -n "${actions}" ]]; then
        local step=1
        while IFS= read -r action; do
            output+="${step}. ${action}\n"
            step=$((step + 1))
        done <<< "${actions}"
    else
        output+="_(No resolution steps recorded)_\n"
    fi
    output+="\n"

    # Root cause
    output+="## Root Cause\n\n"
    local root_cause
    root_cause=$(echo "${incident}" | jq -r '.root_cause // "Not determined"')
    output+="${root_cause}\n\n"

    # Prevention
    output+="## Prevention\n\n"
    local prevention
    prevention=$(echo "${incident}" | jq -r '.prevention // [] | .[]' 2>/dev/null || true)
    if [[ -n "${prevention}" ]]; then
        while IFS= read -r item; do
            output+="- ${item}\n"
        done <<< "${prevention}"
    else
        output+="_(No prevention measures recorded)_\n"
    fi

    local outfile="${DOCGEN_OUTPUT_DIR}/runbook-${incident_id}.md"
    echo -e "${output}"
    echo -e "${output}" > "${outfile}"
    log_info "Runbook generated: ${outfile}"
}

# Generate Architecture Decision Record.
# Usage: docgen_adr <title> <context> <decision> <consequences>
docgen_adr() {
    local title="$1"
    local context="$2"
    local decision="$3"
    local consequences="$4"
    _docgen_init

    local adr_dir="${DOCGEN_OUTPUT_DIR}/adr"
    mkdir -p "${adr_dir}"

    # Find next ADR number
    local next_num=1
    local last_adr
    last_adr=$(ls "${adr_dir}"/???-*.md 2>/dev/null | sort | tail -1 || true)
    if [[ -n "${last_adr}" ]]; then
        local last_num
        last_num=$(basename "${last_adr}" | grep -oP '^\d+' || echo "0")
        next_num=$((10#${last_num} + 1))
    fi

    local slug
    slug=$(echo "${title}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g')
    local filename
    filename=$(printf "%03d-%s.md" "${next_num}" "${slug}")

    local output=""
    output+="# ADR-${next_num}: ${title}\n\n"
    output+="- **Date**: $(date +%Y-%m-%d)\n"
    output+="- **Status**: Proposed\n\n"
    output+="## Context\n\n${context}\n\n"
    output+="## Decision\n\n${decision}\n\n"
    output+="## Consequences\n\n${consequences}\n"

    local outfile="${adr_dir}/${filename}"
    echo -e "${output}" > "${outfile}"
    echo -e "${output}"
    log_info "ADR generated: ${outfile}"
}
