#!/usr/bin/env bash
# OTTO - Infrastructure as Code Pair Programming Assistant
# Generate scaffolds and templates for common IaC tools with best practices.
set -euo pipefail

# Guard against double-sourcing
if [[ -n "${_OTTO_IAC_ASSISTANT_LOADED:-}" ]]; then
    return 0 2>/dev/null || true
fi
_OTTO_IAC_ASSISTANT_LOADED=1

OTTO_DIR="${OTTO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
OTTO_HOME="${OTTO_HOME:-${HOME}/.config/otto}"

# shellcheck source=/dev/null
source "${OTTO_DIR}/scripts/lib/logging.sh"

# --- Public API ---

# Generate a Terraform module skeleton with best practices.
# Usage: iac_scaffold_terraform <name> <provider> <resources_comma_separated> [output_dir]
iac_scaffold_terraform() {
    local name="$1"
    local provider="${2:-aws}"
    local resources="${3:-}"
    local output_dir="${4:-./${name}}"

    mkdir -p "${output_dir}"

    cat > "${output_dir}/main.tf" << EOF
# Terraform module: ${name}
# Provider: ${provider}
# Generated by OTTO

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    ${provider} = {
      source  = "hashicorp/${provider}"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    # Configure your backend
  }
}

provider "${provider}" {
  # Configure provider settings
}

# TODO: Add resources: ${resources:-none specified}
EOF

    cat > "${output_dir}/variables.tf" << 'EOF'
variable "environment" {
  description = "Deployment environment (dev, staging, prod)"
  type        = string
  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be dev, staging, or prod."
  }
}

variable "tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default     = {}
}
EOF

    cat > "${output_dir}/outputs.tf" << 'EOF'
# Define outputs here
EOF

    cat > "${output_dir}/versions.tf" << 'EOF'
# Pin provider versions here
EOF

    cat > "${output_dir}/.terraform-docs.yml" << 'EOF'
formatter: markdown table
output:
  file: README.md
  mode: inject
sort:
  enabled: true
  by: required
EOF

    log_info "Terraform scaffold created at ${output_dir}"
    log_info "Best practices applied: required_version, backend, validation, docs config"
}

# Generate an Ansible role skeleton.
# Usage: iac_scaffold_ansible <name> <role_type> [output_dir]
iac_scaffold_ansible() {
    local name="$1"
    local role_type="${2:-service}"
    local output_dir="${3:-./roles/${name}}"

    for dir in tasks handlers templates files defaults vars meta; do
        mkdir -p "${output_dir}/${dir}"
    done

    cat > "${output_dir}/tasks/main.yml" << EOF
---
# Tasks for ${name} (${role_type})
# Generated by OTTO

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: [${name}, always]

- name: Install ${name} packages
  ansible.builtin.package:
    name: "{{ ${name//-/_}_packages }}"
    state: present
  tags: [${name}, install]

- name: Configure ${name}
  ansible.builtin.template:
    src: ${name}.conf.j2
    dest: "{{ ${name//-/_}_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart ${name}
  tags: [${name}, configure]
EOF

    cat > "${output_dir}/handlers/main.yml" << EOF
---
- name: Restart ${name}
  ansible.builtin.service:
    name: ${name}
    state: restarted
    enabled: true
EOF

    cat > "${output_dir}/defaults/main.yml" << EOF
---
# Default variables for ${name}
${name//-/_}_packages: []
${name//-/_}_config_path: "/etc/${name}/${name}.conf"
${name//-/_}_enabled: true
EOF

    cat > "${output_dir}/meta/main.yml" << EOF
---
galaxy_info:
  role_name: ${name}
  description: "Ansible role for ${name} (${role_type})"
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
    - name: EL
      versions: [8, 9]
dependencies: []
EOF

    cat > "${output_dir}/templates/${name}.conf.j2" << 'EOF'
# Managed by Ansible - do not edit manually
EOF

    log_info "Ansible role scaffold created at ${output_dir}"
}

# Generate a Helm chart skeleton.
# Usage: iac_scaffold_helm <name> <app_type> [output_dir]
iac_scaffold_helm() {
    local name="$1"
    local app_type="${2:-web}"
    local output_dir="${3:-./${name}}"

    mkdir -p "${output_dir}/templates" "${output_dir}/templates/tests"

    cat > "${output_dir}/Chart.yaml" << EOF
apiVersion: v2
name: ${name}
description: Helm chart for ${name} (${app_type})
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: OTTO
EOF

    cat > "${output_dir}/values.yaml" << EOF
# Default values for ${name}
replicaCount: 2

image:
  repository: ${name}
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: ${name}.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]
EOF

    cat > "${output_dir}/templates/deployment.yaml" << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
EOF

    cat > "${output_dir}/templates/_helpers.tpl" << 'EOF'
{{- define "chart.fullname" -}}
{{ .Release.Name }}-{{ .Chart.Name }}
{{- end }}

{{- define "chart.labels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "chart.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
EOF

    log_info "Helm chart scaffold created at ${output_dir}"
}

# Generate a Dockerfile with best practices.
# Usage: iac_scaffold_dockerfile <language> <framework> [output_dir]
iac_scaffold_dockerfile() {
    local language="$1"
    local _framework="${2:-none}"
    local output_dir="${3:-.}"

    mkdir -p "${output_dir}"

    case "${language}" in
        python)
            cat > "${output_dir}/Dockerfile" << 'EOF'
# Multi-stage build for Python application
FROM python:3.12-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

FROM python:3.12-slim
RUN groupadd -r app && useradd -r -g app -d /app -s /sbin/nologin app
WORKDIR /app
COPY --from=builder /root/.local /home/app/.local
COPY . .
RUN chown -R app:app /app
USER app
ENV PATH="/home/app/.local/bin:${PATH}"
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=5s CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz')"
CMD ["python", "-m", "app"]
EOF
            ;;
        node|nodejs)
            cat > "${output_dir}/Dockerfile" << 'EOF'
# Multi-stage build for Node.js application
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine
RUN addgroup -S app && adduser -S app -G app
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .
RUN chown -R app:app /app
USER app
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s CMD wget -qO- http://localhost:3000/healthz || exit 1
CMD ["node", "server.js"]
EOF
            ;;
        go|golang)
            cat > "${output_dir}/Dockerfile" << 'EOF'
# Multi-stage build for Go application
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/server .

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/server /server
USER 65534:65534
EXPOSE 8080
HEALTHCHECK NONE
ENTRYPOINT ["/server"]
EOF
            ;;
        *)
            cat > "${output_dir}/Dockerfile" << EOF
# Dockerfile for ${language} application
# Generated by OTTO - customize as needed
FROM ubuntu:24.04
RUN groupadd -r app && useradd -r -g app app
WORKDIR /app
COPY . .
RUN chown -R app:app /app
USER app
EXPOSE 8080
CMD ["./start.sh"]
EOF
            ;;
    esac

    cat > "${output_dir}/.dockerignore" << 'EOF'
.git
.gitignore
*.md
.env
.env.*
node_modules
__pycache__
.pytest_cache
.venv
Dockerfile
docker-compose*.yml
.dockerignore
EOF

    log_info "Dockerfile scaffold created at ${output_dir}/Dockerfile"
}

# Generate CI/CD pipeline configuration.
# Usage: iac_scaffold_cicd <platform> <language> [output_dir]
iac_scaffold_cicd() {
    local platform="$1"
    local language="${2:-generic}"
    local output_dir="${3:-.}"

    case "${platform}" in
        github|github-actions)
            mkdir -p "${output_dir}/.github/workflows"
            cat > "${output_dir}/.github/workflows/ci.yml" << 'EOF'
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Add your test commands here"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Add your build commands here"

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "Add your deploy commands here"
EOF
            log_info "GitHub Actions CI/CD scaffold created"
            ;;
        gitlab)
            cat > "${output_dir}/.gitlab-ci.yml" << 'EOF'
stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Add your test commands here"

build:
  stage: build
  script:
    - echo "Add your build commands here"

deploy:
  stage: deploy
  script:
    - echo "Add your deploy commands here"
  only:
    - main
  environment:
    name: production
EOF
            log_info "GitLab CI/CD scaffold created"
            ;;
        *)
            log_error "Unsupported CI/CD platform: ${platform}. Supported: github, gitlab"
            return 1
            ;;
    esac
}

# Generate Kubernetes manifests (deployment, service, ingress, hpa).
# Usage: iac_scaffold_k8s <app_name> <type> [output_dir]
iac_scaffold_k8s() {
    local app_name="$1"
    local _type="${2:-deployment}"
    local output_dir="${3:-./k8s}"

    mkdir -p "${output_dir}"

    cat > "${output_dir}/deployment.yaml" << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
  labels:
    app.kubernetes.io/name: ${app_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ${app_name}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${app_name}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: ${app_name}
          image: ${app_name}:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
EOF

    cat > "${output_dir}/service.yaml" << EOF
apiVersion: v1
kind: Service
metadata:
  name: ${app_name}
spec:
  selector:
    app.kubernetes.io/name: ${app_name}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
EOF

    cat > "${output_dir}/ingress.yaml" << EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${app_name}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ${app_name}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${app_name}
                port:
                  number: 80
  tls:
    - hosts:
        - ${app_name}.example.com
      secretName: ${app_name}-tls
EOF

    cat > "${output_dir}/hpa.yaml" << EOF
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${app_name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${app_name}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
EOF

    log_info "Kubernetes manifests created at ${output_dir} (deployment, service, ingress, hpa)"
}
