#!/usr/bin/env bash
set -euo pipefail

# OTTO Onboarding System
# Interactive onboarding wizard for new users.

OTTO_ROOT="${OTTO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
CONFIG_DIR="${HOME}/.config/otto"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"

# Source adaptive UX if available
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/adaptive-ux.sh" ]]; then
    # shellcheck source=adaptive-ux.sh
    source "${SCRIPT_DIR}/adaptive-ux.sh"
fi

# ── Helpers ──────────────────────────────────────────────────────────────────

_print_banner() {
    cat <<'BANNER'

   ██████╗ ████████╗████████╗ ██████╗
  ██╔═══██╗╚══██╔══╝╚══██╔══╝██╔═══██╗
  ██║   ██║   ██║      ██║   ██║   ██║
  ██║   ██║   ██║      ██║   ██║   ██║
  ╚██████╔╝   ██║      ██║   ╚██████╔╝
   ╚═════╝    ╚═╝      ╚═╝    ╚═════╝

  DevOps AI Assistant — Onboarding Wizard

BANNER
}

_ask() {
    local prompt="$1"
    local default="${2:-}"
    local result

    if [[ -n "${default}" ]]; then
        printf '%s [%s]: ' "${prompt}" "${default}" >&2
    else
        printf '%s: ' "${prompt}" >&2
    fi

    read -r result
    if [[ -z "${result}" && -n "${default}" ]]; then
        result="${default}"
    fi
    echo "${result}"
}

_ask_choice() {
    local prompt="$1"
    shift
    local options=("$@")

    echo "" >&2
    echo "${prompt}" >&2
    local i=1
    for opt in "${options[@]}"; do
        printf '  %d) %s\n' "${i}" "${opt}" >&2
        i=$((i + 1))
    done
    printf 'Choice [1]: ' >&2

    local choice
    read -r choice
    choice="${choice:-1}"

    if [[ "${choice}" -ge 1 && "${choice}" -le ${#options[@]} ]] 2>/dev/null; then
        echo "${options[$((choice - 1))]}"
    else
        echo "${options[0]}"
    fi
}

_ask_multi() {
    local prompt="$1"
    shift
    local options=("$@")

    echo "" >&2
    echo "${prompt} (comma-separated numbers)" >&2
    local i=1
    for opt in "${options[@]}"; do
        printf '  %d) %s\n' "${i}" "${opt}" >&2
        i=$((i + 1))
    done
    printf 'Choices: ' >&2

    local choices_str
    read -r choices_str

    local selected=()
    IFS=',' read -ra nums <<< "${choices_str}"
    for num in "${nums[@]}"; do
        num=$(echo "${num}" | tr -d ' ')
        if [[ "${num}" -ge 1 && "${num}" -le ${#options[@]} ]] 2>/dev/null; then
            selected+=("${options[$((num - 1))]}")
        fi
    done

    if [[ ${#selected[@]} -eq 0 ]]; then
        echo "none"
    else
        local IFS=','
        echo "${selected[*]}"
    fi
}

# ── Public Functions ─────────────────────────────────────────────────────────

onboarding_detect_stack() {
    local detected=()

    local -A tool_cmds=(
        [docker]="docker"
        [kubectl]="kubectl"
        [terraform]="terraform"
        [ansible]="ansible"
        [helm]="helm"
        [git]="git"
        [aws]="aws"
        [gcloud]="gcloud"
        [az]="az"
        [vagrant]="vagrant"
        [packer]="packer"
        [nginx]="nginx"
        [python3]="python3"
        [node]="node"
        [go]="go"
        [make]="make"
        [jq]="jq"
        [curl]="curl"
        [openssl]="openssl"
    )

    for tool in "${!tool_cmds[@]}"; do
        if command -v "${tool_cmds[${tool}]}" &>/dev/null; then
            detected+=("${tool}")
        fi
    done

    # Check for config files in common locations
    if [[ -f "${HOME}/.kube/config" ]]; then
        detected+=("kubernetes-config")
    fi
    if [[ -f "${HOME}/.aws/credentials" ]]; then
        detected+=("aws-credentials")
    fi
    if [[ -f "${HOME}/.ssh/config" ]]; then
        detected+=("ssh-config")
    fi

    local IFS=','
    echo "${detected[*]}"
}

onboarding_suggest_profile() {
    local detected_tools="${1:-}"

    if [[ "${detected_tools}" == *"terraform"* && "${detected_tools}" == *"kubectl"* ]]; then
        echo "platform-engineer"
    elif [[ "${detected_tools}" == *"kubectl"* || "${detected_tools}" == *"helm"* ]]; then
        echo "k8s-operator"
    elif [[ "${detected_tools}" == *"terraform"* || "${detected_tools}" == *"ansible"* ]]; then
        echo "infra-engineer"
    elif [[ "${detected_tools}" == *"docker"* && "${detected_tools}" == *"git"* ]]; then
        echo "developer"
    else
        echo "general-ops"
    fi
}

onboarding_create_config() {
    local name="${1:-}"
    local level="${2:-beginner}"
    local role="${3:-general}"
    local tools="${4:-}"
    local profile="${5:-general-ops}"

    mkdir -p "${CONFIG_DIR}"

    cat > "${CONFIG_FILE}" <<YAML
# OTTO Configuration
# Generated by onboarding wizard on $(date -Iseconds)

user:
  name: "${name}"
  level: "${level}"
  role: "${role}"

tools:
$(echo "${tools}" | tr ',' '\n' | while read -r t; do
    t=$(echo "${t}" | tr -d ' ')
    [[ -n "${t}" ]] && echo "  - ${t}"
done)

profile: "${profile}"

preferences:
  explanations: $(if [[ "${level}" == "beginner" || "${level}" == "intermediate" ]]; then echo "true"; else echo "false"; fi)
  suggestions: $(if [[ "${level}" == "beginner" ]]; then echo "true"; else echo "false"; fi)
  tutorials: $(if [[ "${level}" == "beginner" ]]; then echo "true"; else echo "false"; fi)
  colors: true
  confirm_destructive: true

notifications:
  enabled: false
  channels: []
YAML

    echo "${CONFIG_FILE}"
}

onboarding_show_quickstart() {
    local config="${1:-${CONFIG_FILE}}"

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  What to do next"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "  1. Run a health check:"
    echo "       otto check"
    echo ""
    echo "  2. Explore available knowledge:"
    echo "       otto knowledge list"
    echo ""
    echo "  3. Ask for help with a task:"
    echo "       otto help <topic>"
    echo ""
    echo "  4. Search troubleshooting guides:"
    echo "       otto troubleshoot <symptom>"
    echo ""
    echo "  5. View or edit your configuration:"
    echo "       otto config show"
    echo "       otto config edit"
    echo ""
    echo "  Config saved to: ${config}"
    echo ""
}

onboarding_interactive_tutorial() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  OTTO Quick Tutorial"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "  OTTO helps you with DevOps tasks by providing:"
    echo ""
    echo "  [Knowledge Engine]"
    echo "    Search best practices, troubleshooting guides,"
    echo "    runbooks, and architecture patterns."
    echo "    Example: otto knowledge search 'pod crashloop'"
    echo ""
    echo "  [Troubleshooting]"
    echo "    Diagnose issues with guided steps."
    echo "    Example: otto troubleshoot 'nginx 502'"
    echo ""
    echo "  [Runbooks]"
    echo "    Step-by-step procedures for common tasks."
    echo "    Example: otto runbook 'ssl renewal'"
    echo ""
    echo "  [Adaptive UX]"
    echo "    OTTO adapts its verbosity to your skill level."
    echo "    Change it anytime: otto config set level advanced"
    echo ""

    local try_it
    try_it=$(_ask "Would you like to try a sample search? (yes/no)" "yes")

    if [[ "${try_it}" == "yes" || "${try_it}" == "y" ]]; then
        echo ""
        echo "  Running: otto knowledge list"
        echo ""
        if [[ -f "${SCRIPT_DIR}/knowledge-engine.sh" ]]; then
            # shellcheck source=knowledge-engine.sh
            source "${SCRIPT_DIR}/knowledge-engine.sh"
            knowledge_list_topics
        else
            echo "  (Knowledge engine not available yet)"
        fi
    fi

    echo ""
    echo "  Tutorial complete! Run 'otto help' anytime for assistance."
    echo ""
}

onboarding_start() {
    _print_banner

    echo "  Welcome to OTTO! Let's get you set up."
    echo ""

    # Step 1: Detect environment
    echo "  Detecting your environment..."
    local detected
    detected=$(onboarding_detect_stack)
    echo "  Found tools: ${detected}"
    echo ""

    # Step 2: Get user name
    local name
    name=$(_ask "  Your name" "${USER:-operator}")

    # Step 3: Experience level
    local level
    level=$(_ask_choice "  What is your DevOps experience level?" \
        "beginner" "intermediate" "advanced" "expert")

    # Step 4: Primary role
    local role
    role=$(_ask_choice "  What is your primary role?" \
        "developer" "sysadmin" "sre" "platform-engineer" "devops-engineer" "security" "other")

    # Step 5: Primary tools
    local tools
    tools=$(_ask_multi "  Which tools do you primarily use?" \
        "terraform" "ansible" "kubernetes" "docker" "aws" "gcp" "azure" \
        "jenkins" "gitlab-ci" "github-actions" "prometheus" "grafana" "nginx")

    # Step 6: Communication channels (simplified)
    local notifications
    notifications=$(_ask "  Enable notifications? (yes/no)" "no")

    # Step 7: Suggest profile
    local profile
    profile=$(onboarding_suggest_profile "${detected},${tools}")
    echo ""
    echo "  Suggested permission profile: ${profile}"
    local accept_profile
    accept_profile=$(_ask "  Accept this profile? (yes/no)" "yes")
    if [[ "${accept_profile}" != "yes" && "${accept_profile}" != "y" ]]; then
        profile=$(_ask_choice "  Select a profile:" \
            "general-ops" "developer" "k8s-operator" "infra-engineer" "platform-engineer" "security-auditor")
    fi

    # Step 8: Create config
    echo ""
    echo "  Creating configuration..."
    local config_path
    config_path=$(onboarding_create_config "${name}" "${level}" "${role}" "${tools}" "${profile}")

    # Set UX level
    if type ux_set_level &>/dev/null; then
        ux_set_level "${level}" > /dev/null
    fi

    # Step 9: Show quickstart
    onboarding_show_quickstart "${config_path}"

    # Offer tutorial for beginners
    if [[ "${level}" == "beginner" ]]; then
        local run_tutorial
        run_tutorial=$(_ask "  Would you like a quick tutorial? (yes/no)" "yes")
        if [[ "${run_tutorial}" == "yes" || "${run_tutorial}" == "y" ]]; then
            onboarding_interactive_tutorial
        fi
    fi

    echo "  Onboarding complete! Welcome aboard, ${name}."
    echo ""
}

# ── CLI Entry Point ──────────────────────────────────────────────────────────

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cmd="${1:-start}"
    shift || true

    case "${cmd}" in
        start)          onboarding_start ;;
        detect-stack)   onboarding_detect_stack ;;
        suggest)        onboarding_suggest_profile "$@" ;;
        create-config)  onboarding_create_config "$@" ;;
        quickstart)     onboarding_show_quickstart "$@" ;;
        tutorial)       onboarding_interactive_tutorial ;;
        help|*)
            echo "OTTO Onboarding System"
            echo ""
            echo "Usage: onboarding.sh <command> [args...]"
            echo ""
            echo "Commands:"
            echo "  start                        Run the onboarding wizard"
            echo "  detect-stack                 Detect installed tools"
            echo "  suggest <tools>              Suggest permission profile"
            echo "  create-config <args...>      Create config from parameters"
            echo "  quickstart                   Show quickstart guide"
            echo "  tutorial                     Run interactive tutorial"
            ;;
    esac
fi
